{% set version = "3.0.4" %}

package:
  name: swagger-spec-validator
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Yelp/swagger_spec_validator/archive/v{{ version }}.tar.gz
  sha256: 4ac92170d30554bfa71330f89bad74f9b3ef4cc1f594bebb8e8901b3d999c7bf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pyyaml
    - typing_extensions

  run:
    - python >={{ python_min }}
    - jsonschema
    - six
    - setuptools
    - pyyaml
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - swagger_spec_validator

about:
  home: http://github.com/Yelp/swagger_spec_validator
  license: Apache-2.0
  summary: Validation of Swagger specifications
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: http://github.com/Yelp/swagger_spec_validator
  doc_url: http://swagger-spec-validator.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
