schema_version: 1

context:
  version: "3.0.4"

package:
  name: swagger-spec-validator
  version: ${{ version }}

source:
  url: https://github.com/Yelp/swagger_spec_validator/archive/v${{ version }}.tar.gz
  sha256: 4ac92170d30554bfa71330f89bad74f9b3ef4cc1f594bebb8e8901b3d999c7bf

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - jsonschema
    - pyyaml
    - typing_extensions
    - importlib-resources >=1.3

tests:
  - python:
      imports:
        - swagger_spec_validator
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pytest
    files:
      source:
        - tests/
    script:
      - pytest -vv

about:
  license: Apache-2.0
  summary: Validation of Swagger specifications
  license_file: LICENSE.txt
  homepage: http://github.com/Yelp/swagger_spec_validator
  repository: http://github.com/Yelp/swagger_spec_validator
  documentation: http://swagger-spec-validator.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - mgorny
